### ISSUE TITLE
Please be compatible with version 2020.2. Thank you.

### ISSUE THREAD

**Issue by housemea** [liuhao2050/to-go-struct-intellij-plugin#3]
Please be compatible with version 2020.2. Thank you.

**Comment by liuhao2050** [comment]
Thanks for your request, I will fix this ASAP.

**Comment by liuhao2050** [comment]
![image](https://user-images.githubusercontent.com/6995870/89365829-0ca3e800-d708-11ea-9467-e558cf9f4c94.png)

**Comment by liuhao2050** [comment]
Version 1.0.7 of the Convert JSON/SQL to GO Struct plugin has been approved by JetBrains and is now publicly available by the following link: https://plugins.jetbrains.com/plugin/14409-convert-json-sql-to-go-struct/versions/stable/96030.
Enjoy! 🏂
