### ISSUE TITLE
请问官方没有更新包吗, 并且marketpplace 搜索不到

### ISSUE THREAD

**Issue by MerlinFeng** [liuhao2050/to-go-struct-intellij-plugin#4]
![image](https://user-images.githubusercontent.com/10216292/90383573-e6d8f480-e0b2-11ea-9aba-1adfff380a61.png)

![image](https://user-images.githubusercontent.com/10216292/90383795-3a4b4280-e0b3-11ea-9bc1-253adcce0604.png)

**Comment by liuhao2050** [comment]
我会尽快适配一下，晚些给你答复

**Comment by liuhao2050** [comment]
新的版本已经过审，可以到商店进行下载, enjoy！ 🏂 
https://plugins.jetbrains.com/plugin/14409-convert-json-sql-to-go-struct
