### ISSUE TITLE
一些问题以及建议

### ISSUE THREAD

**Issue by wilinz** [liuhao2050/to-go-struct-intellij-plugin#5]
转换后字段名不符合golang命名规范，例如驼峰命名转换后只有首字母是大写，其他都变成了小写，还有的就是建议支持自定义结构体反引号内的sql映射的key，比如 gorm、db等等。还有个地方就是plugin.xml中你设置适用ide版本最高为202，导致最新版goland无法安装也无法在ide里搜索到此插件

**Comment by wilinz** [comment]
我所说的不符合命名规则是当原字段名中有驼峰命名时才会发生

**Comment by liuhao2050** [comment]
感谢建议，下个版本准备修复这些问题，还有准备在下个版本添加选项额外生成CRUD函数，还有什么好的idea咩？
