### ISSUE TITLE
为何要过滤包含“key”的字段，这样做会导致形如 "keyword" 的字段被过滤掉

### ISSUE THREAD

**Issue by wilinz** [liuhao2050/to-go-struct-intellij-plugin#8]
override fun accept(t: SQLColumnDefinition) {
//        这个判断会跳过一些字段，比如 keyword 字段
//        if (t.nameAsString.toUpperCase().contains("KEY")) {
//            return
//        }
        cols.add(t)
    }

**Comment by liuhao2050** [comment]
这个bug已知，会在下个版本修复。

**Comment by liuhao2050** [comment]
主要是有些SQL创建语句中存在索引创建字段 ，`KEY`关键字 也会被识别出来，这里换成equals就可以了

**Comment by liuhao2050** [comment]
在下个版本中我准备加一些CRUD的生成方法。还有把comment也加进去。
